version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  build-and-test:
    docker:
      # This is a pre-built CircleCI Docker image with the Maven and OpenJDK installed
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Build Package
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target
          destination: maven_artifacts

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build-and-test
