CREATE DATABASE IF NOT EXISTS communitydb;

USE communitydb;

CREATE TABLE IF NOT EXISTS Video (
	videoId INT PRIMARY KEY AUTO_INCREMENT,
	userId INT NOT NULL,
	location VARCHAR(255),
	description TEXT,
	video_url VARCHAR(255) NOT NULL,
	postedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	likes INT DEFAULT 0
);

ALTER TABLE Video ADD reports INT DEFAULT 0;

CREATE TABLE IF NOT EXISTS Comment (
    commentId INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    videoId VARCHAR(255) NOT NULL,
    comment TEXT NOT NULL,
    postedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Like` (
    likeId INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    videoId VARCHAR(255) NOT NULL,
    postedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
