name: React Native CI with jest tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile-app

    steps:
      - uses: actions/checkout@v2.4.4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            mobile-app:
              - 'mobile-app/**'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install npm
        run: npm ci

      - name: Jest Tests
        run: npm test
